---
title: "Intro - 1st Blog Post"
date: 2018-12-13
---
title: { K-Fly's Web Dev Blog }
author: Kaitlyn Flynn
email: kaitlynflynn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thank you for showing interest in my blog! I plan to document 
  my journey on becoming a Web Developer here so please check
  back regularly for the latest updates.
  
# social links
github_username:  https://github.com/kaitlynflynn

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
